name: alephant-horse
favicon: null
layout_spectrum: 0.23003
typography_spectrum: 0.8044
title: Natural Leadership Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76161586-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8893191262613982
  lightness: 0.47098906128667295
  saturation: 0.974102494539693
  rhythmicContrast: 0.9826544655952603
purpose: []
